os:
  - linux
  - osx
  # Disabled because of weird failure on Node.js 10 on Windows.
  # - windows
language: node_js
node_js:
  - '14'
  - '12'
  - '10'
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
